import type { OsintTool } from './types'

export const TOOLS: OsintTool[] = [
  // —— Search engines ——
  {
    id: 'google',
    name: 'Google',
    category: 'search-engines',
    subcategory: 'web',
    url: 'https://www.google.com/',
    description: 'General web search with operators (site:, filetype:, cache:, inurl:).',
    tags: ['dorking', 'web', 'operators'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query'],
    notes: 'Queries are logged by Google. Prefer a research account and VPN/Tor policy.',
  },
  {
    id: 'duckduckgo',
    name: 'DuckDuckGo',
    category: 'search-engines',
    url: 'https://duckduckgo.com/',
    description: 'Privacy-oriented search with bangs and a useful !g/!w/!wayback set.',
    tags: ['privacy', 'web', 'bangs'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'bing',
    name: 'Bing',
    category: 'search-engines',
    url: 'https://www.bing.com/',
    description: 'Microsoft search; often indexes pages and image results Google misses.',
    tags: ['web', 'images'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'yandex',
    name: 'Yandex',
    category: 'search-engines',
    url: 'https://yandex.com/',
    description: 'Strong on CIS-language web, reverse image, and cache variants.',
    tags: ['web', 'images', 'cis'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query', 'image'],
  },
  {
    id: 'startpage',
    name: 'Startpage',
    category: 'search-engines',
    url: 'https://www.startpage.com/',
    description: 'Google results via a privacy proxy; useful when you want Google ranking without a Google session.',
    tags: ['privacy', 'web'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'searx-space',
    name: 'SearXNG instances',
    category: 'search-engines',
    url: 'https://searx.space/',
    description: 'Directory of public SearXNG metasearch instances.',
    tags: ['metasearch', 'self-host', 'privacy'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
    notes: 'Trust of a public instance varies; prefer a known-good or self-hosted instance.',
  },
  {
    id: 'google-scholar',
    name: 'Google Scholar',
    category: 'search-engines',
    subcategory: 'academic',
    url: 'https://scholar.google.com/',
    description: 'Scholarly literature, citations, and author profiles.',
    tags: ['academic', 'papers'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query', 'name'],
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    category: 'search-engines',
    url: 'https://search.brave.com/',
    description: 'Independent web index with optional Goggles ranking.',
    tags: ['web', 'independent-index'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'mojeek',
    name: 'Mojeek',
    category: 'search-engines',
    url: 'https://www.mojeek.com/',
    description: 'Independent crawler-based search engine (UK).',
    tags: ['web', 'independent-index'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'wolfram-alpha',
    name: 'Wolfram Alpha',
    category: 'search-engines',
    subcategory: 'computational',
    url: 'https://www.wolframalpha.com/',
    description: 'Computational knowledge engine for facts, units, and structured queries.',
    tags: ['facts', 'compute'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'inteltechniques',
    name: 'IntelTechniques',
    category: 'search-engines',
    subcategory: 'workbook',
    url: 'https://inteltechniques.com/tools/',
    description: 'Michael Bazzell search tool hub (many query builders).',
    tags: ['workbook', 'query-builder'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['query', 'email', 'username', 'name'],
  },

  // —— Social media ——
  {
    id: 'x-advanced',
    name: 'X / Twitter advanced search',
    category: 'social-media',
    url: 'https://x.com/search-advanced',
    description: 'Operator-style search for posts, accounts, dates, and engagement.',
    tags: ['twitter', 'posts'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query', 'username'],
    notes: 'Login walls and rate limits change frequently.',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'social-media',
    url: 'https://www.facebook.com/',
    description: 'Public pages, groups, and Graph Search remnants; most content is login-gated.',
    tags: ['profiles', 'pages'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['name', 'query'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'social-media',
    url: 'https://www.instagram.com/',
    description: 'Public posts, stories highlights, and location tags.',
    tags: ['photos', 'geotags'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username', 'query'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social-media',
    url: 'https://www.linkedin.com/',
    description: 'Professional profiles, company pages, and job history.',
    tags: ['people', 'company'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['name', 'company'],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    category: 'social-media',
    url: 'https://www.reddit.com/',
    description: 'Public forums; use site:reddit.com dorks and old.reddit.com for simpler HTML.',
    tags: ['forums', 'usernames'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'username'],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'social-media',
    url: 'https://www.tiktok.com/',
    description: 'Short video, sounds, and geotagged public posts.',
    tags: ['video', 'geotags'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username', 'query'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'social-media',
    url: 'https://www.youtube.com/',
    description: 'Video search, channel metadata, and published timestamps.',
    tags: ['video', 'channels'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query', 'username'],
  },
  {
    id: 'vk',
    name: 'VK',
    category: 'social-media',
    url: 'https://vk.com/',
    description: 'Public posts, albums, and people search widely used in CIS countries.',
    tags: ['cis', 'people'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['name', 'username'],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'social-media',
    url: 'https://telegram.org/',
    description: 'Public channels and bots; t.me links resolve channel names.',
    tags: ['messaging', 'channels'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username', 'query'],
  },
  {
    id: 'tgstat',
    name: 'TGStat',
    category: 'social-media',
    subcategory: 'telegram analytics',
    url: 'https://tgstat.com/',
    description: 'Public Telegram channel analytics, search, and rankings.',
    tags: ['telegram', 'analytics'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query', 'username'],
  },
  {
    id: 'mastodon',
    name: 'Join Mastodon',
    category: 'social-media',
    url: 'https://joinmastodon.org/',
    description: 'Entry to the fediverse; search is instance-local unless a global search is used.',
    tags: ['fediverse'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['username', 'query'],
  },
  {
    id: 'snap-map',
    name: 'Snap Map',
    category: 'social-media',
    url: 'https://www.snapchat.com/map',
    description: 'Public Snap Map heatmap and location snaps.',
    tags: ['geotags', 'maps'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'social-searcher',
    name: 'Social Searcher',
    category: 'social-media',
    url: 'https://www.social-searcher.com/',
    description: 'Public social mention search across several networks.',
    tags: ['mentions'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },

  // —— Domain & network ——
  {
    id: 'who-is',
    name: 'Who.is',
    category: 'domain-network',
    url: 'https://who.is/',
    description: 'WHOIS and DNS lookup frontend.',
    tags: ['whois', 'dns'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },
  {
    id: 'icann-lookup',
    name: 'ICANN Lookup',
    category: 'domain-network',
    url: 'https://lookup.icann.org/',
    description: 'Authoritative RDAP/WHOIS lookup for gTLDs.',
    tags: ['whois', 'rdap'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },
  {
    id: 'crtsh',
    name: 'crt.sh',
    category: 'domain-network',
    url: 'https://crt.sh/',
    description: 'Certificate Transparency log search; enumerates hostnames from issued certs.',
    tags: ['tls', 'subdomains'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },
  {
    id: 'dnsdumpster',
    name: 'DNSdumpster',
    category: 'domain-network',
    url: 'https://dnsdumpster.com/',
    description: 'DNS recon with mapped records and related hosts.',
    tags: ['dns', 'subdomains'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },
  {
    id: 'viewdns',
    name: 'ViewDNS',
    category: 'domain-network',
    url: 'https://viewdns.info/',
    description: 'Suite of DNS, reverse IP, WHOIS history, and port tools.',
    tags: ['dns', 'whois', 'reverse-ip'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['domain', 'ip'],
  },
  {
    id: 'securitytrails',
    name: 'SecurityTrails',
    category: 'domain-network',
    url: 'https://securitytrails.com/',
    description: 'Historical DNS, WHOIS, and associated infrastructure.',
    tags: ['dns-history', 'whois'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['domain', 'ip'],
  },
  {
    id: 'shodan',
    name: 'Shodan',
    category: 'domain-network',
    url: 'https://www.shodan.io/',
    description: 'Internet-wide device and service banner search.',
    tags: ['banners', 'iot', 'ports'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip', 'query', 'domain'],
  },
  {
    id: 'censys',
    name: 'Censys Search',
    category: 'domain-network',
    url: 'https://search.censys.io/',
    description: 'Internet hosts, certificates, and services dataset.',
    tags: ['hosts', 'tls'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip', 'domain', 'query'],
  },
  {
    id: 'urlscan',
    name: 'urlscan.io',
    category: 'domain-network',
    url: 'https://urlscan.io/',
    description: 'URL and domain scan sandbox with screenshots and request graphs.',
    tags: ['url', 'sandbox'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['url', 'domain'],
    notes: 'Submitting a URL fetches it from urlscan infrastructure (active).',
  },
  {
    id: 'mxtoolbox',
    name: 'MXToolbox',
    category: 'domain-network',
    url: 'https://mxtoolbox.com/',
    description: 'MX, SPF, DKIM, blacklist, and SMTP diagnostics.',
    tags: ['mail', 'dns', 'blacklist'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['domain', 'ip'],
  },
  {
    id: 'he-bgp',
    name: 'Hurricane Electric BGP Toolkit',
    category: 'domain-network',
    url: 'https://bgp.he.net/',
    description: 'ASN, prefix, and peering lookup.',
    tags: ['bgp', 'asn'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['asn', 'ip', 'domain'],
  },
  {
    id: 'ripe-stat',
    name: 'RIPE Stat',
    category: 'domain-network',
    url: 'https://stat.ripe.net/',
    description: 'Routing, geolocation, and whois widgets for prefixes and ASNs.',
    tags: ['ripe', 'bgp'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['ip', 'asn'],
  },
  {
    id: 'bgpview',
    name: 'BGPView',
    category: 'domain-network',
    url: 'https://bgpview.io/',
    description: 'ASN, prefix, and peer visualization.',
    tags: ['bgp', 'asn'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['asn', 'ip'],
  },
  {
    id: 'ipinfo',
    name: 'IPinfo',
    category: 'domain-network',
    url: 'https://ipinfo.io/',
    description: 'IP geolocation, ASN, privacy, and hosted domains.',
    tags: ['ip', 'geo'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip'],
  },
  {
    id: 'abuseipdb',
    name: 'AbuseIPDB',
    category: 'domain-network',
    url: 'https://www.abuseipdb.com/',
    description: 'Community IP abuse reports and CIDR checks.',
    tags: ['abuse', 'ip'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip'],
  },
  {
    id: 'builtwith',
    name: 'BuiltWith',
    category: 'domain-network',
    url: 'https://builtwith.com/',
    description: 'Technology stack fingerprinting for websites.',
    tags: ['fingerprint', 'cms'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['domain', 'url'],
  },
  {
    id: 'securityheaders',
    name: 'Security Headers',
    category: 'domain-network',
    url: 'https://securityheaders.com/',
    description: 'HTTP security-header grader.',
    tags: ['http', 'headers'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'greynoise',
    name: 'GreyNoise',
    category: 'domain-network',
    url: 'https://www.greynoise.io/',
    description: 'Internet scanner noise vs targeted activity classification.',
    tags: ['noise', 'scanners'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip'],
  },
  {
    id: 'leakix',
    name: 'LeakIX',
    category: 'domain-network',
    url: 'https://leakix.net/',
    description: 'Publicly exposed services and leak-like findings from internet scans.',
    tags: ['exposure', 'scan-index'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain', 'ip', 'query'],
  },
  {
    id: 'netcraft',
    name: 'Netcraft Site Report',
    category: 'domain-network',
    url: 'https://sitereport.netcraft.com/',
    description: 'Hosting history, netblock, and site technology report.',
    tags: ['hosting', 'history'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },
  {
    id: 'zoomeye',
    name: 'ZoomEye',
    category: 'domain-network',
    url: 'https://www.zoomeye.org/',
    description: 'Cyberspace search engine (devices and web components).',
    tags: ['cyberspace', 'devices'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query', 'ip', 'domain'],
  },

  // —— Email ——
  {
    id: 'hibp',
    name: 'Have I Been Pwned',
    category: 'email',
    url: 'https://haveibeenpwned.com/',
    description: 'Checks whether an email or phone appears in known public breach corpora.',
    tags: ['breaches', 'passwords'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['email', 'phone'],
  },
  {
    id: 'hunter',
    name: 'Hunter',
    category: 'email',
    url: 'https://hunter.io/',
    description: 'Domain email pattern finder and verifier.',
    tags: ['finder', 'domain'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['domain', 'email', 'name'],
  },
  {
    id: 'emailrep',
    name: 'EmailRep',
    category: 'email',
    url: 'https://emailrep.io/',
    description: 'Reputation lookup for email addresses.',
    tags: ['reputation'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['email'],
  },
  {
    id: 'epieos',
    name: 'Epieos',
    category: 'email',
    url: 'https://epieos.com/',
    description: 'Email and phone OSINT lookups across public traces.',
    tags: ['email', 'phone'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['email', 'phone'],
  },
  {
    id: 'holehe',
    name: 'holehe',
    category: 'email',
    url: 'https://github.com/megadose/holehe',
    description: 'Checks if an email is registered on various sites (self-run).',
    tags: ['cli', 'registration-check'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['email'],
    notes: 'Active: talks to third-party sites from your IP unless proxied.',
  },
  {
    id: 'theharvester',
    name: 'theHarvester',
    category: 'email',
    url: 'https://github.com/laramies/theHarvester',
    description: 'Classic OSINT gatherer for emails, names, and subdomains from public sources.',
    tags: ['cli', 'recon-ng-adjacent'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['domain'],
  },

  // —— Image & video ——
  {
    id: 'google-images',
    name: 'Google Images',
    category: 'image-video',
    url: 'https://images.google.com/',
    description: 'Reverse image search and visual similar-image lookup.',
    tags: ['reverse-image'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['image', 'query'],
  },
  {
    id: 'tineye',
    name: 'TinEye',
    category: 'image-video',
    url: 'https://tineye.com/',
    description: 'Reverse image search with first-seen dates.',
    tags: ['reverse-image', 'dates'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['image', 'url'],
  },
  {
    id: 'yandex-images',
    name: 'Yandex Images',
    category: 'image-video',
    url: 'https://yandex.com/images/',
    description: 'Often the strongest reverse-image engine for faces and outdoor scenes.',
    tags: ['reverse-image', 'faces'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['image'],
  },
  {
    id: 'invid',
    name: 'InVID WeVerify',
    category: 'image-video',
    url: 'https://www.invid-project.eu/tools-and-services/invid-verification-plugin/',
    description: 'Video and image verification toolkit (keyframes, reverse search, metadata).',
    tags: ['verification', 'video'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url', 'image'],
  },
  {
    id: 'fotoforensics',
    name: 'FotoForensics',
    category: 'image-video',
    url: 'https://fotoforensics.com/',
    description: 'Error Level Analysis and basic image forensics.',
    tags: ['ela', 'forensics'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['image'],
    notes: 'Uploading an image shares it with the service.',
  },
  {
    id: 'amnesty-youtube',
    name: 'YouTube DataViewer (Amnesty)',
    category: 'image-video',
    url: 'https://citizenevidence.amnestyusa.org/',
    description: 'Extracts upload time and reverse-image thumbnails from YouTube URLs.',
    tags: ['youtube', 'verification'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'suncalc',
    name: 'SunCalc',
    category: 'image-video',
    subcategory: 'shadows',
    url: 'https://www.suncalc.org/',
    description: 'Sun position and shadow angles for geolocation / time-of-day estimates.',
    tags: ['geolocation', 'shadows'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'pimeyes',
    name: 'PimEyes',
    category: 'image-video',
    url: 'https://pimeyes.com/',
    description: 'Face search across public web imagery. High privacy impact.',
    tags: ['faces', 'biometric'],
    opsec: 'active',
    pricing: 'paid',
    inputs: ['image'],
    notes: 'Use only with lawful purpose; biometric search is legally restricted in many jurisdictions.',
  },

  // —— People search ——
  {
    id: 'truepeoplesearch',
    name: 'TruePeopleSearch',
    category: 'people-search',
    url: 'https://www.truepeoplesearch.com/',
    description: 'US people search from public records aggregators.',
    tags: ['us', 'records'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'phone', 'email'],
  },
  {
    id: 'fastpeoplesearch',
    name: 'FastPeopleSearch',
    category: 'people-search',
    url: 'https://www.fastpeoplesearch.com/',
    description: 'US people and address directory.',
    tags: ['us', 'records'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'phone'],
  },
  {
    id: 'thatsthem',
    name: "That's Them",
    category: 'people-search',
    url: 'https://thatsthem.com/',
    description: 'US people, email, phone, and VIN search.',
    tags: ['us', 'email', 'phone'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'email', 'phone'],
  },
  {
    id: 'whitepages',
    name: 'Whitepages',
    category: 'people-search',
    url: 'https://www.whitepages.com/',
    description: 'US people and reverse-phone directory.',
    tags: ['us', 'phone'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['name', 'phone'],
  },
  {
    id: 'familysearch',
    name: 'FamilySearch',
    category: 'people-search',
    url: 'https://www.familysearch.org/',
    description: 'Free genealogical records and family trees.',
    tags: ['genealogy'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name'],
  },
  {
    id: 'webmii',
    name: 'WebMii',
    category: 'people-search',
    url: 'https://webmii.com/',
    description: 'People search across public web mentions.',
    tags: ['mentions'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name'],
  },
  {
    id: 'uk-192',
    name: '192.com',
    category: 'people-search',
    url: 'https://www.192.com/',
    description: 'UK people, business, and director search.',
    tags: ['uk', 'directors'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['name', 'company'],
  },

  // —— Geolocation ——
  {
    id: 'google-maps',
    name: 'Google Maps',
    category: 'geolocation',
    url: 'https://maps.google.com/',
    description: 'Satellite, Street View, and place search.',
    tags: ['maps', 'streetview'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query', 'coordinates'],
  },
  {
    id: 'osm',
    name: 'OpenStreetMap',
    category: 'geolocation',
    url: 'https://www.openstreetmap.org/',
    description: 'Open map data; excellent for POIs and rural naming.',
    tags: ['maps', 'open-data'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'coordinates'],
  },
  {
    id: 'overpass',
    name: 'Overpass Turbo',
    category: 'geolocation',
    url: 'https://overpass-turbo.eu/',
    description: 'Query OSM data with Overpass QL.',
    tags: ['osm', 'query'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'coordinates'],
  },
  {
    id: 'wikimapia',
    name: 'Wikimapia',
    category: 'geolocation',
    url: 'https://wikimapia.org/',
    description: 'Crowdsourced place labels over satellite imagery.',
    tags: ['labels', 'satellite'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates', 'query'],
  },
  {
    id: 'mapillary',
    name: 'Mapillary',
    category: 'geolocation',
    url: 'https://www.mapillary.com/',
    description: 'Crowdsourced street-level imagery.',
    tags: ['street-level'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'sentinel-hub',
    name: 'Sentinel Hub EO Browser',
    category: 'geolocation',
    url: 'https://apps.sentinel-hub.com/eo-browser/',
    description: 'Sentinel/Landsat/MODIS browser for recent satellite scenes.',
    tags: ['satellite', 'sentinel'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['coordinates'],
  },
  {
    id: 'zoom-earth',
    name: 'Zoom Earth',
    category: 'geolocation',
    url: 'https://zoom.earth/',
    description: 'Near-real-time satellite, weather, and fire overlays.',
    tags: ['satellite', 'weather', 'fires'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'what3words',
    name: 'what3words',
    category: 'geolocation',
    url: 'https://what3words.com/',
    description: 'Three-word geocodes for approximately three-meter squares.',
    tags: ['geocode'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates', 'query'],
  },
  {
    id: 'peakvisor',
    name: 'PeakVisor',
    category: 'geolocation',
    url: 'https://peakvisor.com/',
    description: 'Mountain identification and panorama matching.',
    tags: ['terrain', 'mountains'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['image', 'coordinates'],
  },
  {
    id: 'bellingcat-toolkit',
    name: 'Bellingcat Online Investigation Toolkit',
    category: 'geolocation',
    url: 'https://bellingcat.gitbook.io/toolkit',
    description: 'Curated investigative toolkit covering geolocation and other OSINT disciplines.',
    tags: ['toolkit', 'bellingcat'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Threat intelligence ——
  {
    id: 'virustotal',
    name: 'VirusTotal',
    category: 'threat-intelligence',
    url: 'https://www.virustotal.com/',
    description: 'Multi-engine file, URL, domain, and IP reputation.',
    tags: ['malware', 'url', 'hash'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['hash', 'url', 'domain', 'ip', 'file'],
    notes: 'Uploading a unique file shares it with AV vendors.',
  },
  {
    id: 'malwarebazaar',
    name: 'MalwareBazaar',
    category: 'threat-intelligence',
    url: 'https://bazaar.abuse.ch/',
    description: 'Malware sample sharing platform by abuse.ch.',
    tags: ['malware', 'hash'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['hash'],
  },
  {
    id: 'urlhaus',
    name: 'URLhaus',
    category: 'threat-intelligence',
    url: 'https://urlhaus.abuse.ch/',
    description: 'Database of malicious URLs.',
    tags: ['url', 'malware'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url', 'domain'],
  },
  {
    id: 'threatfox',
    name: 'ThreatFox',
    category: 'threat-intelligence',
    url: 'https://threatfox.abuse.ch/',
    description: 'IOC sharing for IPs, domains, and hashes.',
    tags: ['ioc'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['ip', 'domain', 'hash'],
  },
  {
    id: 'otx',
    name: 'AlienVault OTX',
    category: 'threat-intelligence',
    url: 'https://otx.alienvault.com/',
    description: 'Open threat exchange pulses and indicator lookup.',
    tags: ['ioc', 'community'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['ip', 'domain', 'hash'],
  },
  {
    id: 'hybrid-analysis',
    name: 'Hybrid Analysis',
    category: 'threat-intelligence',
    url: 'https://www.hybrid-analysis.com/',
    description: 'Falcon Sandbox malware reports.',
    tags: ['sandbox', 'malware'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['hash', 'file'],
  },
  {
    id: 'anyrun',
    name: 'ANY.RUN',
    category: 'threat-intelligence',
    url: 'https://any.run/',
    description: 'Interactive malware sandbox.',
    tags: ['sandbox'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['file', 'url', 'hash'],
  },
  {
    id: 'malpedia',
    name: 'Malpedia',
    category: 'threat-intelligence',
    url: 'https://malpedia.caad.fkie.fraunhofer.de/',
    description: 'Malware family encyclopedia from Fraunhofer FKIE.',
    tags: ['families', 'encyclopedia'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'talos',
    name: 'Cisco Talos Intelligence',
    category: 'threat-intelligence',
    url: 'https://talosintelligence.com/',
    description: 'Reputation, email, and malware intelligence.',
    tags: ['reputation'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['ip', 'domain', 'email'],
  },
  {
    id: 'pulsedive',
    name: 'Pulsedive',
    category: 'threat-intelligence',
    url: 'https://pulsedive.com/',
    description: 'Threat intelligence search across indicators and articles.',
    tags: ['ioc', 'search'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['ip', 'domain', 'hash', 'query'],
  },

  // —— Metadata ——
  {
    id: 'exiftool',
    name: 'ExifTool',
    category: 'metadata',
    url: 'https://exiftool.org/',
    description: 'The standard local metadata reader/writer for files.',
    tags: ['exif', 'cli', 'local'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['file'],
    notes: 'Prefer local analysis; do not upload sensitive files to online viewers.',
  },
  {
    id: 'jeffreys-exif',
    name: "Jeffrey's Image Metadata Viewer",
    category: 'metadata',
    url: 'https://exif.regex.info/exif.cgi',
    description: 'Online EXIF/IPTC/XMP viewer.',
    tags: ['exif', 'online'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['image', 'url'],
  },
  {
    id: 'metadata2go',
    name: 'Metadata2Go',
    category: 'metadata',
    url: 'https://www.metadata2go.com/',
    description: 'Online metadata extraction for many file types.',
    tags: ['exif', 'documents'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['file'],
  },
  {
    id: 'mediainfo',
    name: 'MediaInfo',
    category: 'metadata',
    url: 'https://mediaarea.net/en/MediaInfo',
    description: 'Container and codec metadata for audio/video.',
    tags: ['video', 'local'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['file'],
  },
  {
    id: 'exif-tools-online',
    name: 'exif.tools',
    category: 'metadata',
    url: 'https://exif.tools/',
    description: 'Browser EXIF viewer.',
    tags: ['exif'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['image'],
  },

  // —— Documents ——
  {
    id: 'documentcloud',
    name: 'DocumentCloud',
    category: 'document-content',
    url: 'https://www.documentcloud.org/',
    description: 'Public document sets used by journalists.',
    tags: ['documents', 'ocr'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'worldcat',
    name: 'WorldCat',
    category: 'document-content',
    url: 'https://search.worldcat.org/',
    description: 'Global library catalog.',
    tags: ['libraries', 'books'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'archive-texts',
    name: 'Internet Archive Texts',
    category: 'document-content',
    url: 'https://archive.org/details/texts',
    description: 'Scanned books, manuals, and public documents.',
    tags: ['books', 'archive'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'occrp-aleph',
    name: 'OCCRP Aleph',
    category: 'document-content',
    url: 'https://aleph.occrp.org/',
    description: 'Investigative document and entity search platform.',
    tags: ['leaks', 'entities'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'name', 'company'],
  },
  {
    id: 'scribd',
    name: 'Scribd',
    category: 'document-content',
    url: 'https://www.scribd.com/',
    description: 'User-uploaded documents and books.',
    tags: ['documents'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'google-patents',
    name: 'Google Patents',
    category: 'document-content',
    url: 'https://patents.google.com/',
    description: 'Patent full-text search.',
    tags: ['patents'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'name', 'company'],
  },
  {
    id: 'intelx',
    name: 'Intelligence X',
    category: 'document-content',
    url: 'https://intelx.io/',
    description: 'Search engine for leaked data, historical records, and darknet captures.',
    tags: ['leaks', 'selectors'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['email', 'domain', 'query'],
  },

  // —— Code ——
  {
    id: 'github',
    name: 'GitHub',
    category: 'code-repository',
    url: 'https://github.com/',
    description: 'Code hosting; search code, issues, gists, and users.',
    tags: ['git', 'code-search'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query', 'username'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'code-repository',
    url: 'https://gitlab.com/explore',
    description: 'Public GitLab.com projects.',
    tags: ['git'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query', 'username'],
  },
  {
    id: 'grep-app',
    name: 'grep.app',
    category: 'code-repository',
    url: 'https://grep.app/',
    description: 'Fast regex search across public GitHub.',
    tags: ['code-search', 'regex'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'searchcode',
    name: 'searchcode',
    category: 'code-repository',
    url: 'https://searchcode.com/',
    description: 'Code search across multiple forges.',
    tags: ['code-search'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'sourcegraph',
    name: 'Sourcegraph',
    category: 'code-repository',
    url: 'https://sourcegraph.com/search',
    description: 'Indexed code search across public repositories.',
    tags: ['code-search'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'gist',
    name: 'GitHub Gist',
    category: 'code-repository',
    url: 'https://gist.github.com/',
    description: 'Public snippet paste service; often contains keys and configs.',
    tags: ['snippets'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'username'],
  },
  {
    id: 'libraries-io',
    name: 'Libraries.io',
    category: 'code-repository',
    url: 'https://libraries.io/',
    description: 'Package registry metadata across ecosystems.',
    tags: ['packages'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'publicwww',
    name: 'PublicWWW',
    category: 'code-repository',
    url: 'https://publicwww.com/',
    description: 'Source-code search of the public web (JS, widgets, IDs).',
    tags: ['html', 'js'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },

  // —— Usernames ——
  {
    id: 'whatsmyname',
    name: 'WhatsMyName Web',
    category: 'username-tracking',
    url: 'https://whatsmyname.app/',
    description: 'Checks a username against hundreds of sites (WhatsMyName dataset).',
    tags: ['handles', 'enumeration'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username'],
  },
  {
    id: 'sherlock',
    name: 'Sherlock',
    category: 'username-tracking',
    url: 'https://github.com/sherlock-project/sherlock',
    description: 'CLI username hunter across social networks.',
    tags: ['cli', 'handles'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username'],
  },
  {
    id: 'namechk',
    name: 'Namechk',
    category: 'username-tracking',
    url: 'https://namechk.com/',
    description: 'Username and domain availability checker.',
    tags: ['availability'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username', 'domain'],
  },
  {
    id: 'instant-username',
    name: 'Instant Username Search',
    category: 'username-tracking',
    url: 'https://instantusername.com/',
    description: 'Fast username availability across platforms.',
    tags: ['availability'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['username'],
  },
  {
    id: 'idcrawl',
    name: 'IDCrawl',
    category: 'username-tracking',
    url: 'https://www.idcrawl.com/',
    description: 'Username, email, and people search aggregator.',
    tags: ['aggregator'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['username', 'name', 'email'],
  },

  // —— Phone ——
  {
    id: 'truecaller',
    name: 'Truecaller',
    category: 'phone-research',
    url: 'https://www.truecaller.com/',
    description: 'Caller ID and reverse phone powered by crowdsourced address books.',
    tags: ['reverse-phone'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['phone'],
  },
  {
    id: 'numlookup',
    name: 'NumLookup',
    category: 'phone-research',
    url: 'https://www.numlookup.com/',
    description: 'Reverse phone lookup.',
    tags: ['reverse-phone'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['phone'],
  },
  {
    id: 'phoneinfoga',
    name: 'PhoneInfoga',
    category: 'phone-research',
    url: 'https://github.com/sundowndev/phoneinfoga',
    description: 'Information gathering framework for phone numbers (self-run).',
    tags: ['cli', 'osint'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['phone'],
  },
  {
    id: 'spydialer',
    name: 'SpyDialer',
    category: 'phone-research',
    url: 'https://www.spydialer.com/',
    description: 'US reverse phone with voicemail-drop feature (use lawfully).',
    tags: ['us', 'reverse-phone'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['phone'],
  },
  {
    id: 'itu-ton',
    name: 'ITU numbering resources',
    category: 'phone-research',
    url: 'https://www.itu.int/en/ITU-T/inr/Pages/default.aspx',
    description: 'Official national numbering plan resources (country codes, ranges).',
    tags: ['e164', 'official'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['phone'],
  },

  // —— Archives ——
  {
    id: 'wayback',
    name: 'Wayback Machine',
    category: 'web-archive',
    url: 'https://web.archive.org/',
    description: 'Historical snapshots of the public web.',
    tags: ['archive', 'time'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'archive-today',
    name: 'archive.today',
    category: 'web-archive',
    url: 'https://archive.today/',
    description: 'On-demand snapshot archive (also archive.is / archive.ph).',
    tags: ['archive', 'snapshot'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'memento',
    name: 'Memento Time Travel',
    category: 'web-archive',
    url: 'https://timetravel.mementoweb.org/',
    description: 'Aggregates multiple web archives for a URL and datetime.',
    tags: ['memento', 'time'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'cachedview',
    name: 'CachedView',
    category: 'web-archive',
    url: 'https://cachedview.com/',
    description: 'Google, Bing, and archive cache jumper.',
    tags: ['cache'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url'],
  },
  {
    id: 'common-crawl',
    name: 'Common Crawl',
    category: 'web-archive',
    url: 'https://commoncrawl.org/',
    description: 'Open web crawl corpus; indexable via CDX and Athena.',
    tags: ['corpus', 'cdx'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url', 'domain'],
  },
  {
    id: 'arquivo',
    name: 'Arquivo.pt',
    category: 'web-archive',
    url: 'https://arquivo.pt/',
    description: 'Portuguese web archive with search.',
    tags: ['national-archive'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['url', 'query'],
  },

  // —— Company ——
  {
    id: 'opencorporates',
    name: 'OpenCorporates',
    category: 'company-org',
    url: 'https://opencorporates.com/',
    description: 'Largest open database of companies.',
    tags: ['registry', 'officers'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['company', 'name'],
  },
  {
    id: 'companies-house',
    name: 'Companies House',
    category: 'company-org',
    url: 'https://find-and-update.company-information.service.gov.uk/',
    description: 'UK company filings, officers, and accounts.',
    tags: ['uk', 'filings'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['company', 'name'],
  },
  {
    id: 'sec-edgar',
    name: 'SEC EDGAR',
    category: 'company-org',
    url: 'https://www.sec.gov/edgar/search/',
    description: 'US securities filings (10-K, 8-K, beneficial ownership).',
    tags: ['us', 'filings'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['company'],
  },
  {
    id: 'openownership',
    name: 'Open Ownership Register',
    category: 'company-org',
    url: 'https://register.openownership.org/',
    description: 'Beneficial ownership data from participating registers.',
    tags: ['ownership'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['company', 'name'],
  },
  {
    id: 'littlesis',
    name: 'LittleSis',
    category: 'company-org',
    url: 'https://littlesis.org/',
    description: 'Who-knows-who database of powerful people and orgs.',
    tags: ['influence', 'graph'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'company'],
  },
  {
    id: 'northdata',
    name: 'North Data',
    category: 'company-org',
    url: 'https://www.northdata.com/',
    description: 'European company filings and network graphs.',
    tags: ['eu', 'filings'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['company'],
  },
  {
    id: 'crunchbase',
    name: 'Crunchbase',
    category: 'company-org',
    url: 'https://www.crunchbase.com/',
    description: 'Startup, funding, and people database.',
    tags: ['startups', 'funding'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['company', 'name'],
  },

  // —— Maritime & aviation ——
  {
    id: 'marinetraffic',
    name: 'MarineTraffic',
    category: 'maritime-aviation',
    url: 'https://www.marinetraffic.com/',
    description: 'AIS vessel tracking and port calls.',
    tags: ['ais', 'vessels'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['vessel', 'coordinates'],
  },
  {
    id: 'vesselfinder',
    name: 'VesselFinder',
    category: 'maritime-aviation',
    url: 'https://www.vesselfinder.com/',
    description: 'AIS map, vessel particulars, and photos.',
    tags: ['ais'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['vessel'],
  },
  {
    id: 'flightradar24',
    name: 'Flightradar24',
    category: 'maritime-aviation',
    url: 'https://www.flightradar24.com/',
    description: 'Global ADS-B / MLAT flight tracking.',
    tags: ['adsb', 'flights'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['flight', 'coordinates'],
  },
  {
    id: 'adsb-exchange',
    name: 'ADS-B Exchange',
    category: 'maritime-aviation',
    url: 'https://globe.adsbexchange.com/',
    description: 'Unfiltered ADS-B map including many blocked aircraft.',
    tags: ['adsb'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['flight', 'coordinates'],
  },
  {
    id: 'opensky',
    name: 'OpenSky Network',
    category: 'maritime-aviation',
    url: 'https://opensky-network.org/',
    description: 'Open ADS-B research network and API.',
    tags: ['adsb', 'api'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['flight', 'coordinates'],
  },
  {
    id: 'celestrak',
    name: 'CelesTrak',
    category: 'maritime-aviation',
    url: 'https://celestrak.org/',
    description: 'Public NORAD two-line element sets (GP) for satellites. HUD samples stations + visual groups.',
    tags: ['tle', 'satellites', 'sgp4'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
    notes: 'Overwatch SAT layer samples TLEs and propagates client-side. Not a full-sky catalog.',
  },
  {
    id: 'flightaware',
    name: 'FlightAware',
    category: 'maritime-aviation',
    url: 'https://www.flightaware.com/',
    description: 'Flight status, history, and tracking.',
    tags: ['flights'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['flight'],
  },

  // —— Visualization ——
  {
    id: 'maltego',
    name: 'Maltego',
    category: 'visualization',
    url: 'https://www.maltego.com/',
    description: 'Link-analysis workbench with transforms over OSINT sources.',
    tags: ['graph', 'transforms'],
    opsec: 'active',
    pricing: 'freemium',
    inputs: ['query', 'domain', 'email', 'name'],
  },
  {
    id: 'gephi',
    name: 'Gephi',
    category: 'visualization',
    url: 'https://gephi.org/',
    description: 'Open-source graph visualization and metrics.',
    tags: ['graph', 'local'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['file'],
  },
  {
    id: 'kumu',
    name: 'Kumu',
    category: 'visualization',
    url: 'https://kumu.io/',
    description: 'Web-based relationship mapping.',
    tags: ['graph'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'cytoscape',
    name: 'Cytoscape',
    category: 'visualization',
    url: 'https://cytoscape.org/',
    description: 'Network visualization originally for bioinformatics; used for OSINT graphs.',
    tags: ['graph', 'local'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['file'],
  },
  {
    id: 'timelinejs',
    name: 'TimelineJS',
    category: 'visualization',
    url: 'https://timeline.knightlab.com/',
    description: 'Narrative timelines from a Google Sheet.',
    tags: ['timeline'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'rawgraphs',
    name: 'RAWGraphs',
    category: 'visualization',
    url: 'https://www.rawgraphs.io/',
    description: 'Open-source vector data visualization.',
    tags: ['charts'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['file'],
  },
  {
    id: 'spiderfoot',
    name: 'SpiderFoot',
    category: 'visualization',
    subcategory: 'automation',
    url: 'https://github.com/smicallef/spiderfoot',
    description: 'Open-source OSINT automation (self-hosted). This dashboard is a catalog/launcher, not a module clone.',
    tags: ['automation', 'self-host'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['domain', 'ip', 'email', 'name'],
  },
  {
    id: 'recon-ng',
    name: 'Recon-ng',
    category: 'visualization',
    subcategory: 'automation',
    url: 'https://github.com/lanmaster53/recon-ng',
    description: 'Modular web recon framework (CLI).',
    tags: ['cli', 'modules'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['domain'],
  },

  // —— News ——
  {
    id: 'google-news',
    name: 'Google News',
    category: 'news-media',
    url: 'https://news.google.com/',
    description: 'News aggregator with local and topic editions.',
    tags: ['news'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'gdelt',
    name: 'GDELT Project',
    category: 'news-media',
    url: 'https://www.gdeltproject.org/',
    description: 'Global news knowledge graph and DOC 2.0 API.',
    tags: ['news', 'api', 'events'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'liveuamap',
    name: 'Live Universal Awareness Map',
    category: 'news-media',
    url: 'https://liveuamap.com/',
    description: 'Crowdsourced geolocated news map (conflict-heavy).',
    tags: ['map', 'conflict'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['coordinates', 'query'],
  },
  {
    id: 'bellingcat',
    name: 'Bellingcat',
    category: 'news-media',
    url: 'https://www.bellingcat.com/',
    description: 'Open-source investigation outlet and method guides.',
    tags: ['investigations'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'ground-news',
    name: 'Ground News',
    category: 'news-media',
    url: 'https://ground.news/',
    description: 'Story clustering with source-bias distribution.',
    tags: ['bias', 'clusters'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'allsides',
    name: 'AllSides',
    category: 'news-media',
    url: 'https://www.allsides.com/',
    description: 'Media bias ratings and side-by-side stories.',
    tags: ['bias'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'osint-framework',
    name: 'OSINT Framework',
    category: 'news-media',
    subcategory: 'directory',
    url: 'https://osintframework.com/',
    description: 'Classic tree directory of OSINT tools (arf.json taxonomy).',
    tags: ['directory', 'taxonomy'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Data & stats ——
  {
    id: 'world-bank',
    name: 'World Bank Open Data',
    category: 'data-statistics',
    url: 'https://data.worldbank.org/',
    description: 'Development indicators by country.',
    tags: ['indicators'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'owid',
    name: 'Our World in Data',
    category: 'data-statistics',
    url: 'https://ourworldindata.org/',
    description: 'Research-grade charts on global issues.',
    tags: ['charts', 'research'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'un-data',
    name: 'UNdata',
    category: 'data-statistics',
    url: 'https://data.un.org/',
    description: 'UN statistical databases.',
    tags: ['un', 'stats'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'oecd',
    name: 'OECD Data',
    category: 'data-statistics',
    url: 'https://data.oecd.org/',
    description: 'OECD country statistics.',
    tags: ['oecd'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'data-gov',
    name: 'Data.gov',
    category: 'data-statistics',
    url: 'https://data.gov/',
    description: 'US federal open data catalog.',
    tags: ['us', 'open-data'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'wikidata',
    name: 'Wikidata',
    category: 'data-statistics',
    url: 'https://www.wikidata.org/',
    description: 'Structured knowledge base; SPARQL at query.wikidata.org.',
    tags: ['knowledge-graph', 'sparql'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'name'],
  },
  {
    id: 'hdx',
    name: 'Humanitarian Data Exchange',
    category: 'data-statistics',
    url: 'https://data.humdata.org/',
    description: 'OCHA humanitarian datasets.',
    tags: ['humanitarian'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'eurostat',
    name: 'Eurostat',
    category: 'data-statistics',
    url: 'https://ec.europa.eu/eurostat',
    description: 'European Union official statistics.',
    tags: ['eu', 'stats'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Privacy ——
  {
    id: 'privacyguides',
    name: 'Privacy Guides',
    category: 'privacy-security',
    url: 'https://www.privacyguides.org/',
    description: 'Vetted privacy tool recommendations.',
    tags: ['opsec', 'guides'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'eff-ssd',
    name: 'EFF Surveillance Self-Defense',
    category: 'privacy-security',
    url: 'https://ssd.eff.org/',
    description: 'Threat-modeling and operational security guides.',
    tags: ['opsec', 'guides'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'tor-project',
    name: 'Tor Project',
    category: 'privacy-security',
    url: 'https://www.torproject.org/',
    description: 'Anonymity network and Tor Browser.',
    tags: ['anonymity'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'tails',
    name: 'Tails',
    category: 'privacy-security',
    url: 'https://tails.net/',
    description: 'Amnesic live OS routing through Tor.',
    tags: ['os', 'amnesic'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'cover-tracks',
    name: 'Cover Your Tracks (EFF)',
    category: 'privacy-security',
    url: 'https://coveryourtracks.eff.org/',
    description: 'Browser fingerprinting test.',
    tags: ['fingerprinting'],
    opsec: 'active',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'twofa-dir',
    name: '2FA Directory',
    category: 'privacy-security',
    url: 'https://2fa.directory/',
    description: 'Which sites support two-factor authentication.',
    tags: ['2fa'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'justdelete-me',
    name: 'JustDeleteMe',
    category: 'privacy-security',
    url: 'https://justdeleteme.xyz/',
    description: 'Directory of account-deletion pages.',
    tags: ['accounts'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Financial ——
  {
    id: 'opensanctions',
    name: 'OpenSanctions',
    category: 'financial',
    url: 'https://www.opensanctions.org/',
    description: 'Open database of sanctioned and politically exposed persons.',
    tags: ['sanctions', 'pep'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['name', 'company'],
  },
  {
    id: 'icij-offshore',
    name: 'ICIJ Offshore Leaks Database',
    category: 'financial',
    url: 'https://offshoreleaks.icij.org/',
    description: 'Search Panama/Paradise/Pandora Papers and related leaks.',
    tags: ['leaks', 'offshore'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'company'],
  },
  {
    id: 'occrp',
    name: 'OCCRP',
    category: 'financial',
    url: 'https://www.occrp.org/',
    description: 'Organized-crime and corruption reporting project.',
    tags: ['investigations'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'finra-brokercheck',
    name: 'FINRA BrokerCheck',
    category: 'financial',
    url: 'https://brokercheck.finra.org/',
    description: 'US broker and firm registration and disclosure search.',
    tags: ['us', 'brokers'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['name', 'company'],
  },
  {
    id: 'etherscan',
    name: 'Etherscan',
    category: 'financial',
    url: 'https://etherscan.io/',
    description: 'Ethereum blockchain explorer.',
    tags: ['crypto', 'ledger'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'blockchain-com',
    name: 'Blockchain.com Explorer',
    category: 'financial',
    url: 'https://www.blockchain.com/explorer',
    description: 'Bitcoin and other public-ledger explorer.',
    tags: ['crypto', 'btc'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'chainabuse',
    name: 'Chainabuse',
    category: 'financial',
    url: 'https://www.chainabuse.com/',
    description: 'Community reports of crypto addresses tied to scams.',
    tags: ['crypto', 'abuse'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Weather ——
  {
    id: 'windy',
    name: 'Windy',
    category: 'weather',
    url: 'https://www.windy.com/',
    description: 'Global weather models, satellite, radar, and webcams.',
    tags: ['models', 'satellite'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['coordinates'],
  },
  {
    id: 'ventusky',
    name: 'Ventusky',
    category: 'weather',
    url: 'https://www.ventusky.com/',
    description: 'Animated global weather visualization.',
    tags: ['models'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'nullschool',
    name: 'earth.nullschool.net',
    category: 'weather',
    url: 'https://earth.nullschool.net/',
    description: 'Global wind, ocean, and chemical visualization.',
    tags: ['wind', 'aerosols'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'lightningmaps',
    name: 'LightningMaps',
    category: 'weather',
    url: 'https://www.lightningmaps.org/',
    description: 'Real-time lightning detection network.',
    tags: ['lightning'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'noaa',
    name: 'NOAA',
    category: 'weather',
    url: 'https://www.noaa.gov/',
    description: 'US weather, climate, and ocean official source.',
    tags: ['official', 'us'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query', 'coordinates'],
  },
  {
    id: 'meteologix',
    name: 'Meteologix',
    category: 'weather',
    url: 'https://meteologix.com/',
    description: 'High-resolution radar, satellite, and model maps.',
    tags: ['radar', 'satellite'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['coordinates'],
  },

  // —— War & conflict ——
  {
    id: 'acled',
    name: 'ACLED',
    category: 'war-conflict',
    url: 'https://acleddata.com/',
    description: 'Armed Conflict Location & Event Data Project.',
    tags: ['events', 'data'],
    opsec: 'passive',
    pricing: 'freemium',
    inputs: ['query'],
  },
  {
    id: 'ucdp',
    name: 'UCDP',
    category: 'war-conflict',
    url: 'https://ucdp.uu.se/',
    description: 'Uppsala Conflict Data Program.',
    tags: ['data', 'academic'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'oryx',
    name: 'Oryx',
    category: 'war-conflict',
    url: 'https://www.oryxspioenkop.com/',
    description: 'Visual-evidence-based equipment loss lists.',
    tags: ['equipment', 'visual'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'isw',
    name: 'Institute for the Study of War',
    category: 'war-conflict',
    url: 'https://www.understandingwar.org/',
    description: 'Campaign assessments and control-of-terrain maps.',
    tags: ['assessments', 'maps'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'airwars',
    name: 'Airwars',
    category: 'war-conflict',
    url: 'https://airwars.org/',
    description: 'Monitoring of civilian harm from airstrikes.',
    tags: ['airstrikes', 'civilians'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'forensic-architecture',
    name: 'Forensic Architecture',
    category: 'war-conflict',
    url: 'https://forensic-architecture.org/',
    description: 'Spatial investigations of state and corporate violence.',
    tags: ['spatial', 'investigations'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'syrian-archive',
    name: 'Syrian Archive',
    category: 'war-conflict',
    url: 'https://syrianarchive.org/',
    description: 'Preserved visual evidence of human-rights violations.',
    tags: ['archive', 'video'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },

  // —— Natural disaster ——
  {
    id: 'usgs-eq',
    name: 'USGS Earthquake Hazards',
    category: 'natural-disaster',
    url: 'https://earthquake.usgs.gov/',
    description: 'Global earthquake feed and maps (GeoJSON, no key).',
    tags: ['earthquakes', 'geojson'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'gdacs',
    name: 'GDACS',
    category: 'natural-disaster',
    url: 'https://www.gdacs.org/',
    description: 'Global Disaster Alert and Coordination System.',
    tags: ['alerts', 'multi-hazard'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'reliefweb',
    name: 'ReliefWeb',
    category: 'natural-disaster',
    url: 'https://reliefweb.int/',
    description: 'OCHA humanitarian reports and disaster updates.',
    tags: ['humanitarian', 'reports'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'eonet',
    name: 'NASA EONET',
    category: 'natural-disaster',
    url: 'https://eonet.gsfc.nasa.gov/',
    description: 'Earth Observatory Natural Event Tracker.',
    tags: ['fires', 'storms', 'volcanoes'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'firms',
    name: 'NASA FIRMS',
    category: 'natural-disaster',
    url: 'https://firms.modaps.eosdis.nasa.gov/',
    description: 'Fire Information for Resource Management (MODIS/VIIRS hotspots).',
    tags: ['fires', 'satellite'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'nhc',
    name: 'National Hurricane Center',
    category: 'natural-disaster',
    url: 'https://www.nhc.noaa.gov/',
    description: 'Atlantic and eastern Pacific tropical cyclone official advisories.',
    tags: ['hurricanes', 'official'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'nifc-perimeters',
    name: 'NIFC WFIGS perimeters',
    category: 'natural-disaster',
    url: 'https://data-nifc.opendata.arcgis.com/',
    description: 'Current US interagency wildfire perimeters as public ArcGIS GeoJSON (WFIGS).',
    tags: ['fires', 'perimeters', 'geojson'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
    notes: 'HUD NIFC layer samples the largest current perimeters. Empty/ERR if the service moves — nothing is invented.',
  },
  {
    id: 'tsunami-gov',
    name: 'Tsunami.gov',
    category: 'natural-disaster',
    url: 'https://www.tsunami.gov/',
    description: 'US Tsunami Warning System.',
    tags: ['tsunami', 'official'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
  {
    id: 'gfw',
    name: 'Global Forest Watch',
    category: 'natural-disaster',
    url: 'https://www.globalforestwatch.org/',
    description: 'Near-real-time forest change and fire alerts.',
    tags: ['forests', 'fires'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['coordinates'],
  },
  {
    id: 'copernicus-ems',
    name: 'Copernicus Emergency Management',
    category: 'natural-disaster',
    url: 'https://emergency.copernicus.eu/',
    description: 'EU satellite mapping activations for disasters.',
    tags: ['satellite', 'eu'],
    opsec: 'passive',
    pricing: 'free',
    inputs: ['query'],
  },
]
